import streamlit as st
import pandas as pd
import altair as alt
import google.generativeai as genai
import joblib
import os

# === CONFIGURATION ===
st.set_page_config(page_title="AutoOps AI", page_icon="🤖", layout="wide")

# === LOAD MODEL (Cached for Speed) ===
@st.cache_resource
def load_model():
    # In the cloud, the file is just in the 'model' folder
    return joblib.load("model/model_v1.pkl")

try:
    model = load_model()
except Exception as e:
    st.error(f"Error loading model: {e}")
    st.stop()

# === SESSION STATE ===
if 'total_charges' not in st.session_state:
    st.session_state['total_charges'] = 600.0

def update_total():
    if 'monthly_charges' in st.session_state and 'tenure' in st.session_state:
        st.session_state.total_charges = float(st.session_state.tenure * st.session_state.monthly_charges)

# === GEMINI SELECTOR ===
def get_gemini_response(api_key, prompt):
    genai.configure(api_key=api_key)
    candidates = ["gemini-2.5-flash", "gemini-3-flash", "gemini-2.0-flash-exp", "gemini-1.5-flash", "gemini-pro"]
    for model_name in candidates:
        try:
            m = genai.GenerativeModel(model_name)
            response = m.generate_content(prompt)
            return f"**✅ Strategy (Generated by {model_name}):**\n\n{response.text}"
        except:
            continue
    return "❌ AI Strategy Failed. Check API Key."

# === SIDEBAR ===
with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/8637/8637103.png", width=80)
    st.header("AutoOps AI")
    st.markdown("Top 1% Churn Intelligence System")
    
    # Secret Key Management for Cloud
    api_key = st.secrets.get("GEMINI_API_KEY", None)
    if not api_key:
        api_key = os.getenv("GEMINI_API_KEY") 

    st.success("🟢 System Online") if api_key else st.warning("⚠️ AI Key Missing")

st.title("🤖 Customer Retention Intelligence System")
st.markdown("#### *Real-time Churn Prediction + Gemini Strategic Advice*")

# === UI FORM ===
st.subheader("📋 Customer Profile")
c1, c2, c3 = st.columns(3)

with c1:
    gender = st.selectbox("Gender", ["Male", "Female"])
    SeniorCitizen = st.selectbox("Senior Citizen", [0, 1])
    tenure = st.slider("Tenure (Months)", 0, 72, 12, key="tenure", on_change=update_total)

with c2:
    Contract = st.selectbox("Contract", ["Month-to-month", "One year", "Two year"])
    MonthlyCharges = st.number_input("Monthly Charges ($)", value=50.0, step=5.0, key="monthly_charges", on_change=update_total)
    TotalCharges = st.number_input("Total Charges ($)", value=st.session_state.total_charges, key="total_charges")

with c3:
    InternetService = st.selectbox("Internet", ["Fiber optic", "DSL", "No"])
    PaymentMethod = st.selectbox("Payment", ["Electronic check", "Mailed check", "Bank transfer (automatic)", "Credit card (automatic)"])
    TechSupport = st.selectbox("Tech Support", ["No", "Yes", "No internet service"])

with st.expander("🛠️ Advanced Demographic & Service Fields"):
    Partner = st.selectbox("Partner", ["No", "Yes"])
    Dependents = st.selectbox("Dependents", ["No", "Yes"])
    PhoneService = st.selectbox("Phone Service", ["Yes", "No"])
    MultipleLines = st.selectbox("Multiple Lines", ["No", "Yes", "No phone service"])
    OnlineSecurity = st.selectbox("Online Security", ["No", "Yes", "No internet service"])
    PaperlessBilling = st.selectbox("Paperless Billing", ["Yes", "No"])

others = {"OnlineBackup": "No", "DeviceProtection": "No", "StreamingTV": "No", "StreamingMovies": "No"}

if st.button("🚀 Run Analysis", type="primary"):
    # Prepare Data
    input_data = {
        **others,
        "gender": gender, "SeniorCitizen": int(SeniorCitizen), "Partner": Partner, "Dependents": Dependents,
        "tenure": int(tenure), "PhoneService": PhoneService, "MultipleLines": MultipleLines,
        "InternetService": InternetService, "OnlineSecurity": OnlineSecurity, "TechSupport": TechSupport,
        "Contract": Contract, "PaperlessBilling": PaperlessBilling, "PaymentMethod": PaymentMethod,
        "MonthlyCharges": float(MonthlyCharges), "TotalCharges": float(TotalCharges)
    }
    
    # DataFrame for Model
    df = pd.DataFrame([input_data])
    
    # PREDICTION
    pred = model.predict(df)[0]
    prob = model.predict_proba(df)[0][1]
    
    st.divider()
    col_res, col_why = st.columns([1, 2])
    
    with col_res:
        st.subheader("Risk Analysis")
        risk_score = f"{prob * 100:.1f}%"
        if pred == 1:
            st.error("🚨 HIGH RISK")
            st.metric("Churn Probability", risk_score, "Critical")
        else:
            st.success("✅ LOYAL")
            st.metric("Churn Probability", risk_score, "Stable")

    with col_why:
        st.subheader("📉 Root Cause & Strategy")
        
        # Feature Importance
        classifier = model.named_steps['classifier']
        importances = classifier.feature_importances_
        feature_names = ["Contract Type", "Monthly Cost", "Total Spend", "Tenure", "Tech Support", "Internet Type", "Payment Method"]
        # Safe match
        count = min(len(feature_names), len(importances))
        scores = importances[:count]
        
        df_chart = pd.DataFrame({"Factor": feature_names[:count], "Impact": scores})
        df_chart = df_chart.sort_values(by="Impact", ascending=False).head(3)
        
        chart = alt.Chart(df_chart).mark_bar(color='#FF4B4B').encode(
            x='Impact', y=alt.Y('Factor', sort='-x')
        ).properties(height=200)
        st.altair_chart(chart, use_container_width=True)
        
        top_features_text = ", ".join(df_chart['Factor'].tolist())

        # Gemini
        st.subheader("🧠 Gemini Strategic Agent")
        if not api_key:
            st.warning("Please add GEMINI_API_KEY in Streamlit Secrets.")
        else:
            with st.spinner("Generating strategy..."):
                prompt = f"""
                Act as a Retention Manager.
                Customer Risk: {prob*100:.1f}% (High is bad).
                Bill: ${MonthlyCharges}. Top Drivers: {top_features_text}.
                
                1. Diagnosis (1 sentence).
                2. Retention Offer.
                3. Short phone script.
                """
                st.info(get_gemini_response(api_key, prompt))