import streamlit as st
import requests
import pandas as pd
import altair as alt
import google.generativeai as genai
import os
from dotenv import load_dotenv

# 1. Load Env
load_dotenv()
api_key = os.getenv("GEMINI_API_KEY")

st.set_page_config(page_title="AutoOps AI", page_icon="🤖", layout="wide")

# 2. Session State (Smart Math)
if 'total_charges' not in st.session_state:
    st.session_state['total_charges'] = 600.0

def update_total():
    if 'monthly_charges' in st.session_state and 'tenure' in st.session_state:
        st.session_state.total_charges = float(st.session_state.tenure * st.session_state.monthly_charges)

# 3. Smart Gemini Selector (The Fix for 404 Errors)
def get_gemini_response(api_key, prompt):
    genai.configure(api_key=api_key)
    candidates = ["gemini-2.5-flash", "gemini-3-flash", "gemini-2.0-flash-exp", "gemini-1.5-flash", "gemini-pro"]
    errors = []
    for model_name in candidates:
        try:
            model = genai.GenerativeModel(model_name)
            response = model.generate_content(prompt)
            return f"**✅ Strategy (Generated by {model_name}):**\n\n{response.text}"
        except Exception as e:
            errors.append(f"{model_name}: {str(e)}")
            continue 
    return f"❌ AI Strategy Failed. Debug Log:\n" + "\n".join(errors)

# 4. Sidebar
with st.sidebar:
    st.header("🧠 System Status")
    if api_key:
        st.success("🔑 Gemini Key Loaded")
    else:
        st.error("❌ No API Key Found")
    st.markdown("---")
    st.markdown("**Model:** Random Forest v1.6.1\n**Metric:** Real-time Probability")

st.title("🤖 Customer Retention Intelligence System")

# 5. UI FORM
st.subheader("📋 Customer Profile")
c1, c2, c3 = st.columns(3)

with c1:
    gender = st.selectbox("Gender", ["Male", "Female"])
    SeniorCitizen = st.selectbox("Senior Citizen", [0, 1])
    tenure = st.slider("Tenure (Months)", 0, 72, 12, key="tenure", on_change=update_total)
    
with c2:
    Contract = st.selectbox("Contract", ["Month-to-month", "One year", "Two year"])
    MonthlyCharges = st.number_input("Monthly Charges ($)", value=50.0, step=5.0, key="monthly_charges", on_change=update_total)
    TotalCharges = st.number_input("Total Charges ($)", value=st.session_state.total_charges, key="total_charges")
    
with c3:
    InternetService = st.selectbox("Internet", ["Fiber optic", "DSL", "No"])
    PaymentMethod = st.selectbox("Payment", ["Electronic check", "Mailed check", "Bank transfer (automatic)", "Credit card (automatic)"])
    TechSupport = st.selectbox("Tech Support", ["No", "Yes", "No internet service"])

with st.expander("🛠️ Advanced Demographic & Service Fields"):
    Partner = st.selectbox("Partner", ["No", "Yes"])
    Dependents = st.selectbox("Dependents", ["No", "Yes"])
    PhoneService = st.selectbox("Phone Service", ["Yes", "No"])
    MultipleLines = st.selectbox("Multiple Lines", ["No", "Yes", "No phone service"])
    OnlineSecurity = st.selectbox("Online Security", ["No", "Yes", "No internet service"])
    PaperlessBilling = st.selectbox("Paperless Billing", ["Yes", "No"])
        
others = {"OnlineBackup": "No", "DeviceProtection": "No", "StreamingTV": "No", "StreamingMovies": "No"}

if st.button("🚀 Run Analysis", type="primary"):
    
    payload = {
        **others,
        "gender": gender, "SeniorCitizen": int(SeniorCitizen), "Partner": Partner, "Dependents": Dependents,
        "tenure": int(tenure), "PhoneService": PhoneService, "MultipleLines": MultipleLines,
        "InternetService": InternetService, "OnlineSecurity": OnlineSecurity, "TechSupport": TechSupport,
        "Contract": Contract, "PaperlessBilling": PaperlessBilling, "PaymentMethod": PaymentMethod,
        "MonthlyCharges": float(MonthlyCharges), "TotalCharges": float(TotalCharges)
    }

    try:
        res = requests.post("http://127.0.0.1:8000/predict", json=payload)
        
        if res.status_code == 200:
            data = res.json()
            pred = data["prediction"]
            prob = data["probability"] # <--- REAL PROBABILITY FROM BACKEND
            
            st.divider()
            
            col_res, col_why = st.columns([1, 2])
            
            with col_res:
                st.subheader("Risk Analysis")
                # Display the REAL percentage
                risk_score = f"{prob * 100:.1f}%"
                
                if pred == 1:
                    st.error("🚨 HIGH RISK")
                    st.metric("Churn Probability", risk_score, "Critical")
                else:
                    st.success("✅ LOYAL")
                    # Inverse probability for loyalty
                    st.metric("Churn Probability", risk_score, "Stable")

            with col_why:
                st.subheader("📉 Root Cause & Strategy")
                
                top_features_text = "None"
                if "importances" in data:
                    feature_names = ["Contract Type", "Monthly Cost", "Total Spend", "Tenure", "Tech Support", "Internet Type", "Payment Method"]
                    count = min(len(feature_names), len(data["importances"]))
                    scores = data["importances"][:count]
                    
                    df_chart = pd.DataFrame({"Factor": feature_names[:count], "Impact": scores})
                    df_chart = df_chart.sort_values(by="Impact", ascending=False).head(3)
                    
                    chart = alt.Chart(df_chart).mark_bar(color='#FF4B4B').encode(
                        x='Impact', y=alt.Y('Factor', sort='-x'), tooltip=['Factor', 'Impact']
                    )
                    st.altair_chart(chart, use_container_width=True)
                    top_features_text = ", ".join([f"{row['Factor']}" for index, row in df_chart.iterrows()])

                st.subheader("🧠 Gemini Strategic Agent")
                
                if not api_key:
                    st.warning("⚠️ Missing API Key in .env")
                else:
                    with st.spinner("Analyzing with AI..."):
                        prompt = f"""
                        Role: Retention Manager.
                        Customer Risk Score: {prob*100:.1f}% (High is bad).
                        Tenure: {tenure} months. Contract: {Contract}. Bill: ${MonthlyCharges}.
                        Top Risk Factors: {top_features_text}.
                        
                        Task:
                        1. Explain the risk score (e.g. "Extremely High" vs "Moderate").
                        2. Propose a specific offer.
                        3. Write a short phone script.
                        """
                        result_text = get_gemini_response(api_key, prompt)
                        st.info(result_text)

        else:
            st.error(f"API Error: {res.text}")
            
    except Exception as e:
        st.error(f"Connection Error: {e}")